name: Cypress Tests

# Triggers the workflow on pushes to the master branch or manual dispatch
on:
  workflow_dispatch: # Allows for manual triggering from the Actions tab

jobs:
  cypress:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Run Cypress tests
        uses: cypress-io/github-action@v6
        env:
          # Pass environment variables from GitHub Secrets
          STANDARD_USERNAME: ${{ secrets.STANDARD_USERNAME }}
          STANDARD_PASSWORD: ${{ secrets.STANDARD_PASSWORD }}
          LOCKEDOUT_USERNAME: ${{ secrets.LOCKEDOUT_USERNAME }}
          LOCKEDOUT_PASSWORD: ${{ secrets.LOCKEDOUT_PASSWORD }}
          PROBLEM_USERNAME: ${{ secrets.PROBLEM_USERNAME }}
          PROBLEM_PASSWORD: ${{ secrets.PROBLEM_PASSWORD }}
          GLITCH_USERNAME: ${{ secrets.GLITCH_USERNAME }}
          GLITCH_PASSWORD: ${{ secrets.GLITCH_PASSWORD }}
